
var upcase = " LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. OBCAECATI MINUS EVENIET AT ODIT, DEBITIS SED REPELLENDUS AUTEM EUM MINIMA QUAERAT SINT NUMQUAM, LIBERO ID NESCIUNT NOBIS ODIO IMPEDIT NATUS SOLUTA.";
var lwcase;

lwcase = upcase.toLowerCase();

console.log(` ${upcase} \n ${lwcase} .`);
